// <auto-generated />
namespace IncosafCMS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Add_KDV_Contracts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_KDV_Contracts));
        
        string IMigrationMetadata.Id
        {
            get { return "201911171648424_Add_KDV_Contracts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
